// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// // app/layout.jsx
// import Link from "next/link";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* Header / Menu */}
//         <header className="bg-gray-800 text-white p-4 flex space-x-4">
//           <Link href="/" className="hover:underline">
//             🎮 Game List
//           </Link>
//           <Link href="/game-crud" className="hover:underline">
//             ⚙️ Game CRUD
//           </Link>
//         </header>

//         {/* Main content */}
//         <main className="p-6">{children}</main>
//       </body>
//     </html>
//   );
// }


// app/layout.jsx
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header / Menu */}
        <header className="bg-gray-800 text-white p-4 flex space-x-4">
          <Link href="/" className="hover:underline">
            🎮 Game List
          </Link>
          <Link href="/game-crud" className="hover:underline">
            ⚙️ Game CRUD
          </Link>
          <Link href="/top-rating" className="hover:underline">
            🏆 Top Rating
          </Link>
          <Link href="/graph-stat" className="hover:underline">
            📊 Graph Rating Stat
          </Link>
          <Link href="/device" className="hover:underline">
            📊 Platform
          </Link>
        </header>

        {/* Main content */}
        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
